# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Yolal\ing_soft\Practica-Ing.software\src\ui\editProfileTutor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContainerEditProfile(object):
    def setupUi(self, ContainerEditProfile):
        ContainerEditProfile.setObjectName("ContainerEditProfile")
        ContainerEditProfile.resize(704, 500)
        ContainerEditProfile.setStyleSheet("")
        self.editProfileFrame = QtWidgets.QFrame(ContainerEditProfile)
        self.editProfileFrame.setGeometry(QtCore.QRect(0, 0, 711, 501))
        self.editProfileFrame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.editProfileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.editProfileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.editProfileFrame.setObjectName("editProfileFrame")
        self.barra = QtWidgets.QWidget(self.editProfileFrame)
        self.barra.setGeometry(QtCore.QRect(0, 0, 61, 501))
        self.barra.setStyleSheet("background-color: rgb(249, 235, 211);\n"
"\n"
"\n"
"")
        self.barra.setObjectName("barra")
        self.boton_usuario = QtWidgets.QPushButton(self.barra)
        self.boton_usuario.setGeometry(QtCore.QRect(20, 110, 24, 24))
        self.boton_usuario.setMaximumSize(QtCore.QSize(200, 100))
        self.boton_usuario.setStyleSheet("\n"
"border-image: url(:/images/home.png);")
        self.boton_usuario.setText("")
        self.boton_usuario.setIconSize(QtCore.QSize(10, 5))
        self.boton_usuario.setObjectName("boton_usuario")
        self.botonasignaturas = QtWidgets.QPushButton(self.barra)
        self.botonasignaturas.setGeometry(QtCore.QRect(20, 150, 24, 24))
        self.botonasignaturas.setStyleSheet("border-image: url(:/images/open-book.png);")
        self.botonasignaturas.setText("")
        self.botonasignaturas.setObjectName("botonasignaturas")
        self.botonhome = QtWidgets.QPushButton(self.barra)
        self.botonhome.setGeometry(QtCore.QRect(20, 70, 24, 24))
        self.botonhome.setStyleSheet("border-image: url(:/images/usuario (4).png);")
        self.botonhome.setText("")
        self.botonhome.setObjectName("botonhome")
        self.logo = QtWidgets.QLabel(self.barra)
        self.logo.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.logo.setStyleSheet("border-image: url(:/images/logoUniConnect.png);\n"
"")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.Botonsalir = QtWidgets.QPushButton(self.barra)
        self.Botonsalir.setGeometry(QtCore.QRect(10, 460, 31, 31))
        self.Botonsalir.setStyleSheet("border-image: url(:/images/cross.png);")
        self.Botonsalir.setText("")
        self.Botonsalir.setObjectName("Botonsalir")
        self.editarPerfilProfile = QtWidgets.QLabel(self.editProfileFrame)
        self.editarPerfilProfile.setGeometry(QtCore.QRect(90, 20, 191, 41))
        self.editarPerfilProfile.setStyleSheet("font: 75 18pt \"Arial\";")
        self.editarPerfilProfile.setObjectName("editarPerfilProfile")
        self.cajaUsuarioLogin = QtWidgets.QLineEdit(self.editProfileFrame)
        self.cajaUsuarioLogin.setGeometry(QtCore.QRect(80, 280, 141, 21))
        self.cajaUsuarioLogin.setStyleSheet("background-color: rgba(0,0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(55, 158, 210);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.cajaUsuarioLogin.setObjectName("cajaUsuarioLogin")
        self.cajaUsuarioLogin_2 = QtWidgets.QLineEdit(self.editProfileFrame)
        self.cajaUsuarioLogin_2.setGeometry(QtCore.QRect(260, 280, 141, 21))
        self.cajaUsuarioLogin_2.setStyleSheet("background-color: rgba(0,0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(55, 158, 210);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.cajaUsuarioLogin_2.setObjectName("cajaUsuarioLogin_2")
        self.cajaUsuarioLogin_3 = QtWidgets.QLineEdit(self.editProfileFrame)
        self.cajaUsuarioLogin_3.setGeometry(QtCore.QRect(80, 230, 141, 21))
        self.cajaUsuarioLogin_3.setStyleSheet("background-color: rgba(0,0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(55, 158, 210);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.cajaUsuarioLogin_3.setObjectName("cajaUsuarioLogin_3")
        self.cajaUsuarioLogin_4 = QtWidgets.QLineEdit(self.editProfileFrame)
        self.cajaUsuarioLogin_4.setGeometry(QtCore.QRect(80, 340, 141, 21))
        self.cajaUsuarioLogin_4.setStyleSheet("background-color: rgba(0,0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(55, 158, 210);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.cajaUsuarioLogin_4.setObjectName("cajaUsuarioLogin_4")
        self.cajaUsuarioLogin_5 = QtWidgets.QLineEdit(self.editProfileFrame)
        self.cajaUsuarioLogin_5.setGeometry(QtCore.QRect(260, 230, 141, 21))
        self.cajaUsuarioLogin_5.setStyleSheet("background-color: rgba(0,0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(55, 158, 210);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.cajaUsuarioLogin_5.setObjectName("cajaUsuarioLogin_5")
        self.espacioFotoEditPorfile = QtWidgets.QLabel(self.editProfileFrame)
        self.espacioFotoEditPorfile.setGeometry(QtCore.QRect(120, 90, 91, 81))
        self.espacioFotoEditPorfile.setStyleSheet("border-image: url(:/images/camara.png);")
        self.espacioFotoEditPorfile.setText("")
        self.espacioFotoEditPorfile.setObjectName("espacioFotoEditPorfile")
        self.botonAddFoto = QtWidgets.QPushButton(self.editProfileFrame)
        self.botonAddFoto.setGeometry(QtCore.QRect(270, 120, 101, 21))
        self.botonAddFoto.setMouseTracking(True)
        self.botonAddFoto.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0681818 rgba(132, 205, 255, 255), stop:1 rgba(85, 74, 208, 255));\n"
"font: 75 9pt \"Arial\";\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(110, 110, 110, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgb(60, 193, 231);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"    \n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.botonAddFoto.setAutoDefault(False)
        self.botonAddFoto.setDefault(False)
        self.botonAddFoto.setObjectName("botonAddFoto")
        self.botonAddFoto_2 = QtWidgets.QPushButton(self.editProfileFrame)
        self.botonAddFoto_2.setGeometry(QtCore.QRect(500, 440, 111, 31))
        self.botonAddFoto_2.setMouseTracking(True)
        self.botonAddFoto_2.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0681818 rgba(132, 205, 255, 255), stop:1 rgba(85, 74, 208, 255));\n"
"font: 75 9pt \"Arial\";\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(110, 110, 110, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgb(60, 193, 231);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"    \n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.botonAddFoto_2.setAutoDefault(False)
        self.botonAddFoto_2.setDefault(False)
        self.botonAddFoto_2.setObjectName("botonAddFoto_2")
        self.cajaUsuarioLogin_6 = QtWidgets.QLineEdit(self.editProfileFrame)
        self.cajaUsuarioLogin_6.setGeometry(QtCore.QRect(260, 340, 141, 21))
        self.cajaUsuarioLogin_6.setStyleSheet("background-color: rgba(0,0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(55, 158, 210);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.cajaUsuarioLogin_6.setText("")
        self.cajaUsuarioLogin_6.setObjectName("cajaUsuarioLogin_6")
        self.editarPerfilProfile_2 = QtWidgets.QLabel(self.editProfileFrame)
        self.editarPerfilProfile_2.setGeometry(QtCore.QRect(90, 180, 151, 41))
        self.editarPerfilProfile_2.setStyleSheet("font: 75 13pt \"Arial\";")
        self.editarPerfilProfile_2.setObjectName("editarPerfilProfile_2")
        self.cuadroDatos = QtWidgets.QLabel(self.editProfileFrame)
        self.cuadroDatos.setGeometry(QtCore.QRect(460, 110, 181, 291))
        self.cuadroDatos.setStyleSheet("background-color: rgb(197, 245, 255);\n"
"border-bottom-color: rgb(45, 33, 173);\n"
"gridline-color: rgb(44, 32, 172);")
        self.cuadroDatos.setText("")
        self.cuadroDatos.setObjectName("cuadroDatos")
        self.editarPerfilProfile_3 = QtWidgets.QLabel(self.editProfileFrame)
        self.editarPerfilProfile_3.setGeometry(QtCore.QRect(490, 110, 121, 41))
        self.editarPerfilProfile_3.setStyleSheet("font: 75 13pt \"Arial\";\n"
"background-color: transparent;")
        self.editarPerfilProfile_3.setObjectName("editarPerfilProfile_3")
        self.cajaUsuarioLogin_8 = QtWidgets.QLineEdit(self.editProfileFrame)
        self.cajaUsuarioLogin_8.setGeometry(QtCore.QRect(80, 390, 141, 21))
        self.cajaUsuarioLogin_8.setStyleSheet("background-color: rgba(0,0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(55, 158, 210);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.cajaUsuarioLogin_8.setObjectName("cajaUsuarioLogin_8")

        self.retranslateUi(ContainerEditProfile)
        QtCore.QMetaObject.connectSlotsByName(ContainerEditProfile)

    def retranslateUi(self, ContainerEditProfile):
        _translate = QtCore.QCoreApplication.translate
        ContainerEditProfile.setWindowTitle(_translate("ContainerEditProfile", "Form"))
        self.editarPerfilProfile.setText(_translate("ContainerEditProfile", "Editar perfil Tutor"))
        self.cajaUsuarioLogin.setPlaceholderText(_translate("ContainerEditProfile", "email"))
        self.cajaUsuarioLogin_2.setPlaceholderText(_translate("ContainerEditProfile", "Grado"))
        self.cajaUsuarioLogin_3.setPlaceholderText(_translate("ContainerEditProfile", "Nombre de usuario"))
        self.cajaUsuarioLogin_4.setPlaceholderText(_translate("ContainerEditProfile", "Contraseña"))
        self.cajaUsuarioLogin_5.setPlaceholderText(_translate("ContainerEditProfile", "Apellido"))
        self.botonAddFoto.setText(_translate("ContainerEditProfile", "Agregar foto"))
        self.botonAddFoto_2.setText(_translate("ContainerEditProfile", "Guardar"))
        self.cajaUsuarioLogin_6.setPlaceholderText(_translate("ContainerEditProfile", "Confirmar contraseña"))
        self.editarPerfilProfile_2.setText(_translate("ContainerEditProfile", "Actualizar datos"))
        self.editarPerfilProfile_3.setText(_translate("ContainerEditProfile", "Datos actuales"))
        self.cajaUsuarioLogin_8.setPlaceholderText(_translate("ContainerEditProfile", "Asignaturas"))
import res_rc
