# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QListWidgetItem
import ui.imagenes.resorces_rc


tasks = ["Escribir email", "Finalizar trabajo", "Mirar tutorial"]

class Ui_ContainerHome(object):
    def setupUi(self, ContainerHome):
        ContainerHome.setObjectName("ContainerHome")
        ContainerHome.resize(704, 500)
        ContainerHome.setStyleSheet("")
        self.frameHome = QtWidgets.QFrame(ContainerHome)
        self.frameHome.setGeometry(QtCore.QRect(0, 0, 711, 501))
        self.frameHome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.frameHome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHome.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHome.setObjectName("frameHome")
        self.barra = QtWidgets.QWidget(self.frameHome)
        self.barra.setGeometry(QtCore.QRect(0, 0, 61, 501))
        self.barra.setStyleSheet("background-color: rgb(249, 235, 211);\n"
"\n"
"\n"
"")
        self.barra.setObjectName("barra")
        self.boton_usuario = QtWidgets.QPushButton(self.barra)
        self.boton_usuario.setGeometry(QtCore.QRect(20, 110, 24, 24))
        self.boton_usuario.setMaximumSize(QtCore.QSize(200, 100))
        self.boton_usuario.setStyleSheet("QPushButton{\n"
"border-image: url(:/imagenes/home.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.boton_usuario.setText("")
        self.boton_usuario.setIconSize(QtCore.QSize(10, 5))
        self.boton_usuario.setObjectName("boton_usuario")
        self.botonasignaturas = QtWidgets.QPushButton(self.barra)
        self.botonasignaturas.setGeometry(QtCore.QRect(20, 150, 24, 24))
        self.botonasignaturas.setStyleSheet("QPushButton{\n"
"border-image: url(:/imagenes/open-book.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.botonasignaturas.setText("")
        self.botonasignaturas.setObjectName("botonasignaturas")
        self.botonhome = QtWidgets.QPushButton(self.barra)
        self.botonhome.setGeometry(QtCore.QRect(20, 70, 24, 24))
        self.botonhome.setStyleSheet("QPushButton{\n"
"border-image: url(:/imagenes/usuario (4).png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"")
        self.botonhome.setText("")
        self.botonhome.setObjectName("botonhome")
        self.logo = QtWidgets.QLabel(self.barra)
        self.logo.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.logo.setStyleSheet("border-image: url(:/imagenes/logoUniConnect.png);\n"
"")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.Botonsalir = QtWidgets.QPushButton(self.barra)
        self.Botonsalir.setGeometry(QtCore.QRect(10, 460, 31, 31))
        self.Botonsalir.setStyleSheet("QPushButton{\n"
"border-image: url(:/imagenes/cross.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.Botonsalir.setText("")
        self.Botonsalir.setObjectName("Botonsalir")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frameHome)
        self.calendarWidget.setGeometry(QtCore.QRect(100, 170, 281, 221))
        self.calendarWidget.setStyleSheet("font: 10pt;\n"
"color: rgb(44, 188, 230);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.listView = QtWidgets.QListView(self.frameHome)
        self.listView.setGeometry(QtCore.QRect(410, 190, 256, 192))
        self.listView.setObjectName("listView")
        self.botonAceptarLogin = QtWidgets.QPushButton(self.frameHome)
        self.botonAceptarLogin.setGeometry(QtCore.QRect(470, 390, 151, 21))
        self.botonAceptarLogin.setMouseTracking(True)
        self.botonAceptarLogin.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0681818 rgba(132, 205, 255, 255), stop:1 rgba(85, 74, 208, 255));\n"
"font: 75 9pt \"Arial\";\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(110, 110, 110, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgb(60, 193, 231);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"    \n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.botonAceptarLogin.setAutoDefault(False)
        self.botonAceptarLogin.setDefault(False)
        self.botonAceptarLogin.setObjectName("botonAceptarLogin")
        self.botonAceptarLogin_2 = QtWidgets.QPushButton(self.frameHome)
        self.botonAceptarLogin_2.setGeometry(QtCore.QRect(550, 160, 111, 21))
        self.botonAceptarLogin_2.setMouseTracking(True)
        self.botonAceptarLogin_2.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0681818 rgba(132, 205, 255, 255), stop:1 rgba(85, 74, 208, 255));\n"
"font: 75 9pt \"Arial\";\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(110, 110, 110, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgb(60, 193, 231);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"    \n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.botonAceptarLogin_2.setAutoDefault(False)
        self.botonAceptarLogin_2.setDefault(False)
        self.botonAceptarLogin_2.setObjectName("botonAceptarLogin_2")
        self.label = QtWidgets.QLabel(self.frameHome)
        self.label.setGeometry(QtCore.QRect(60, 60, 651, 51))
        self.label.setStyleSheet("border-image: url(:/imagenes/FondoDegradado.png);\n"
"font: 75 18pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(ContainerHome)
        QtCore.QMetaObject.connectSlotsByName(ContainerHome)
        self.calendarWidget.selectionChanged.connect(self.calendarDateChanged)
        self.updateTaskList()


    def calendarDateChanged(self):
        print("La fecha del calendario ha sido cambiada.")
        dateSelected = self.calendarWidget.selectedDate().toPyDate()
        print("Fecha seleccionada: ", dateSelected)

    def updateTaskList(self):
        model = QtGui.QStandardItemModel()
        for task in tasks:
            item = QtGui.QStandardItem(task)
            item.setFlags(item.flags() | QtCore.Qt.ItemIsUserCheckable)
            item.setCheckState(QtCore.Qt.Unchecked)
            model.appendRow(item)

        self.listView.setModel(model)

    def retranslateUi(self, ContainerHome):
        _translate = QtCore.QCoreApplication.translate
        ContainerHome.setWindowTitle(_translate("ContainerHome", "Form"))
        self.botonAceptarLogin.setText(_translate("ContainerHome", "Guardar"))
        self.botonAceptarLogin_2.setText(_translate("ContainerHome", "Agregar tarea"))
        self.label.setText(_translate("ContainerHome", "Calendario de tareas"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ContainerHome = QtWidgets.QWidget()
    ui = Ui_ContainerHome()
    ui.setupUi(ContainerHome)
    ContainerHome.show()
    sys.exit(app.exec_())
