# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Yolal\ing_soft\Practica-Ing.software\src\ui\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContainerLogin(object):
    def setupUi(self, ContainerLogin):
        ContainerLogin.setObjectName("ContainerLogin")
        ContainerLogin.resize(704, 500)
        ContainerLogin.setStyleSheet("")
        self.LoginPrincipal = QtWidgets.QFrame(ContainerLogin)
        self.LoginPrincipal.setGeometry(QtCore.QRect(0, 0, 711, 501))
        self.LoginPrincipal.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.LoginPrincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LoginPrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginPrincipal.setObjectName("LoginPrincipal")
        self.esloganLogin = QtWidgets.QLabel(self.LoginPrincipal)
        self.esloganLogin.setGeometry(QtCore.QRect(80, 350, 311, 16))
        self.esloganLogin.setStyleSheet("font: 75 13pt \"Arial\";\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.esloganLogin.setObjectName("esloganLogin")
        self.barra = QtWidgets.QWidget(self.LoginPrincipal)
        self.barra.setGeometry(QtCore.QRect(0, 0, 61, 501))
        self.barra.setStyleSheet("background-color: rgb(249, 235, 211);\n"
"\n"
"\n"
"")
        self.barra.setObjectName("barra")
        self.boton_usuario = QtWidgets.QPushButton(self.barra)
        self.boton_usuario.setGeometry(QtCore.QRect(20, 110, 24, 24))
        self.boton_usuario.setMaximumSize(QtCore.QSize(200, 100))
        self.boton_usuario.setStyleSheet("QPushButton{\n"
"border-image: url(:/imagenes/home.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.boton_usuario.setText("")
        self.boton_usuario.setIconSize(QtCore.QSize(10, 5))
        self.boton_usuario.setObjectName("boton_usuario")
        self.botonasignaturas = QtWidgets.QPushButton(self.barra)
        self.botonasignaturas.setGeometry(QtCore.QRect(20, 150, 24, 24))
        self.botonasignaturas.setStyleSheet("QPushButton{\n"
"border-image: url(:/imagenes/open-book.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.botonasignaturas.setText("")
        self.botonasignaturas.setObjectName("botonasignaturas")
        self.botonhome = QtWidgets.QPushButton(self.barra)
        self.botonhome.setGeometry(QtCore.QRect(20, 70, 24, 24))
        self.botonhome.setStyleSheet("QPushButton{\n"
"border-image: url(:/imagenes/usuario (4).png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.botonhome.setText("")
        self.botonhome.setObjectName("botonhome")
        self.logo = QtWidgets.QLabel(self.barra)
        self.logo.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.logo.setStyleSheet("border-image: url(:/imagenes/logoUniConnect.png);\n"
"")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.Botonsalir = QtWidgets.QPushButton(self.barra)
        self.Botonsalir.setGeometry(QtCore.QRect(10, 460, 31, 31))
        self.Botonsalir.setStyleSheet("QPushButton{\n"
"border-image: url(:/imagenes/cross.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.Botonsalir.setText("")
        self.Botonsalir.setObjectName("Botonsalir")
        self.calendarioHome = QtWidgets.QCalendarWidget(self.LoginPrincipal)
        self.calendarioHome.setGeometry(QtCore.QRect(90, 180, 256, 190))
        self.calendarioHome.setObjectName("calendarioHome")
        self.listaTareasHome = QtWidgets.QListWidget(self.LoginPrincipal)
        self.listaTareasHome.setGeometry(QtCore.QRect(390, 190, 256, 192))
        self.listaTareasHome.setObjectName("listaTareasHome")
        self.botonGuardar = QtWidgets.QPushButton(self.LoginPrincipal)
        self.botonGuardar.setGeometry(QtCore.QRect(450, 400, 141, 21))
        self.botonGuardar.setMouseTracking(True)
        self.botonGuardar.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0681818 rgba(132, 205, 255, 255), stop:1 rgba(85, 74, 208, 255));\n"
"font: 75 9pt \"Arial\";\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(110, 110, 110, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgb(60, 193, 231);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"    \n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.botonGuardar.setAutoDefault(False)
        self.botonGuardar.setDefault(False)
        self.botonGuardar.setObjectName("botonGuardar")
        self.botonAgregar = QtWidgets.QPushButton(self.LoginPrincipal)
        self.botonAgregar.setGeometry(QtCore.QRect(540, 150, 101, 21))
        self.botonAgregar.setMouseTracking(True)
        self.botonAgregar.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0681818 rgba(132, 205, 255, 255), stop:1 rgba(85, 74, 208, 255));\n"
"font: 75 9pt \"Arial\";\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(110, 110, 110, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgb(60, 193, 231);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"    \n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.botonAgregar.setAutoDefault(False)
        self.botonAgregar.setDefault(False)
        self.botonAgregar.setObjectName("botonAgregar")
        self.label = QtWidgets.QLabel(self.LoginPrincipal)
        self.label.setGeometry(QtCore.QRect(60, 90, 651, 41))
        self.label.setStyleSheet("font: 75 18pt \"Arial\";\n"
"border-image: url(:/imagenes/FondoDegradado.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 188, 230);\n"
"border-radius: 8xp;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(ContainerLogin)
        QtCore.QMetaObject.connectSlotsByName(ContainerLogin)

    def retranslateUi(self, ContainerLogin):
        _translate = QtCore.QCoreApplication.translate
        ContainerLogin.setWindowTitle(_translate("ContainerLogin", "Form"))
        self.esloganLogin.setText(_translate("ContainerLogin", "\" Ordena tu mundo, desata tu potencial \""))
        self.botonGuardar.setText(_translate("ContainerLogin", "Guardar"))
        self.botonAgregar.setText(_translate("ContainerLogin", "Agregar tarea"))
        self.label.setText(_translate("ContainerLogin", "Lista de Tareas"))
import res_rc
