# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Yolal\ing_soft\Practica-Ing.software\src\ui\pupil.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContainerLogin(object):
    def setupUi(self, ContainerLogin):
        ContainerLogin.setObjectName("ContainerLogin")
        ContainerLogin.resize(704, 500)
        ContainerLogin.setStyleSheet("")
        self.LoginPrincipal = QtWidgets.QFrame(ContainerLogin)
        self.LoginPrincipal.setGeometry(QtCore.QRect(0, 0, 711, 501))
        self.LoginPrincipal.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.LoginPrincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LoginPrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginPrincipal.setObjectName("LoginPrincipal")
        self.subContainerLogin = QtWidgets.QLabel(self.LoginPrincipal)
        self.subContainerLogin.setGeometry(QtCore.QRect(400, 130, 201, 331))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.subContainerLogin.setFont(font)
        self.subContainerLogin.setStyleSheet("\n"
"background-color: rgb(252, 252, 252);\n"
"")
        self.subContainerLogin.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.subContainerLogin.setText("")
        self.subContainerLogin.setObjectName("subContainerLogin")
        self.esloganLogin = QtWidgets.QLabel(self.LoginPrincipal)
        self.esloganLogin.setGeometry(QtCore.QRect(80, 350, 311, 16))
        self.esloganLogin.setStyleSheet("font: 75 13pt \"Arial\";\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.esloganLogin.setObjectName("esloganLogin")
        self.barra = QtWidgets.QWidget(self.LoginPrincipal)
        self.barra.setGeometry(QtCore.QRect(0, 0, 61, 501))
        self.barra.setStyleSheet("background-color: rgb(249, 235, 211);\n"
"\n"
"\n"
"")
        self.barra.setObjectName("barra")
        self.boton_usuario = QtWidgets.QPushButton(self.barra)
        self.boton_usuario.setGeometry(QtCore.QRect(20, 110, 24, 24))
        self.boton_usuario.setMaximumSize(QtCore.QSize(200, 100))
        self.boton_usuario.setStyleSheet("QPushButton{\n"
"border-image: url(:/images/home.png);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.boton_usuario.setText("")
        self.boton_usuario.setIconSize(QtCore.QSize(10, 5))
        self.boton_usuario.setObjectName("boton_usuario")
        self.botonasignaturas = QtWidgets.QPushButton(self.barra)
        self.botonasignaturas.setGeometry(QtCore.QRect(20, 150, 24, 24))
        self.botonasignaturas.setStyleSheet("QPushButton{\n"
"border-image: url(:/images/open-book.png);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.botonasignaturas.setText("")
        self.botonasignaturas.setObjectName("botonasignaturas")
        self.botonhome = QtWidgets.QPushButton(self.barra)
        self.botonhome.setGeometry(QtCore.QRect(20, 70, 24, 24))
        self.botonhome.setStyleSheet("QPushButton{\n"
"border-image: url(:/images/usuario (4).png);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"")
        self.botonhome.setText("")
        self.botonhome.setObjectName("botonhome")
        self.logo = QtWidgets.QLabel(self.barra)
        self.logo.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.logo.setStyleSheet("border-image: url(:/images/logoUniConnect.png);\n"
"")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.Botonsalir = QtWidgets.QPushButton(self.barra)
        self.Botonsalir.setGeometry(QtCore.QRect(10, 460, 31, 31))
        self.Botonsalir.setStyleSheet("QPushButton{\n"
"    border-image: url(:/images/cross.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.Botonsalir.setText("")
        self.Botonsalir.setObjectName("Botonsalir")
        self.botonaTutelados = QtWidgets.QPushButton(self.barra)
        self.botonaTutelados.setGeometry(QtCore.QRect(20, 190, 24, 24))
        self.botonaTutelados.setStyleSheet("QPushButton{\n"
"    \n"
"    border-image: url(:/images/estudiante (2).png);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.botonaTutelados.setText("")
        self.botonaTutelados.setObjectName("botonaTutelados")
        self.label = QtWidgets.QLabel(self.LoginPrincipal)
        self.label.setGeometry(QtCore.QRect(90, 20, 91, 41))
        self.label.setStyleSheet("font: 15pt \"Arial\";")
        self.label.setObjectName("label")

        self.retranslateUi(ContainerLogin)
        QtCore.QMetaObject.connectSlotsByName(ContainerLogin)

    def retranslateUi(self, ContainerLogin):
        _translate = QtCore.QCoreApplication.translate
        ContainerLogin.setWindowTitle(_translate("ContainerLogin", "Form"))
        self.esloganLogin.setText(_translate("ContainerLogin", "\" Ordena tu mundo, desata tu potencial \""))
        self.label.setText(_translate("ContainerLogin", "Tutelados"))
import res_rc
